---
- include_tasks: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Install Certbot.
  package: "name={{ certbot_package }} state=present"

- name: Set Certbot script variable.
  set_fact:
    certbot_script: "{{ certbot_package }}"
